# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Setting up Terraform"
    cd azure/
    terraform init
  displayName: 'Setup Terraform environment'
- task: AzureCLI@2
  inputs:
    azureSubscription: $(subscription-name)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      export TF_VAR_image_name=$(image-name)
      export TF_VAR_blob_uri=$(blob-uri)
      export TF_VAR_existing_rg=$(existing-rg)
      cd azure/
      terraform apply -auto-approve
  displayName: 'Deploy Azure Resources with Terraform'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(subscription-name)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd azure/
      terraform destroy -auto-approve
  displayName: 'Destroy Azure Resources with Terraform'
  enabled: false

