---
- name: Set image properties
  set_fact:
    publisher: "{{ item.split(':')[0] }}"
    offer: "{{ item.split(':')[1] }}"
    sku: "{{ item.split(':')[2] }}"
    version: "{{ item.split(':')[3] }}"
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set VM name variable
  set_fact:
    vmname: "{{ offer }}-{{ sku }}-{{ version }}"
    
- name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: pbasnal-rg
    name: "{{ vmname }}"
    remove_on_absent: all_autocreated
    state: absent