###
# This Playbook checks if the some specific drivers are blacklisted in the given image
# Author: Anuj Maurya  
###
---

- name: Print RHEL minor version
  debug:
    msg: "ansible_distribution_version: {{ ansible_distribution_version }}"

- name: Check if the drivers are blacklisted using modprobed in all images
  shell: modprobe --showconfig | grep blacklist | grep "blacklist {{item}}"
  register: blacklisted_drivers_allimages
  with_items:
    - nouveau
    - lbm_nouveau
    - floppy
    - skx_edac
    - intel_cstate
    - amdgpu
  ignore_errors: yes

- name: Check if the drivers are  blacklisted in RHEL 8.1 images
  shell: modprobe --showconfig | grep blacklist | grep "blacklist {{item}}"
  register: blacklisted_drivers_specific_rhelversion
  with_items:
    - blacklist intel_uncore
    - blacklist intel_rapl
    - blacklist acpi_cpufreq
  ignore_errors: yes
  when: ansible_distribution_version == "8.1"

- name: Initialize an empty list for storing blacklisted drivers
  set_fact:
    missing_drivers_allimages: []

- name: Initialize an empty list for storing blacklisted drivers for specific images
  set_fact:
    missing_drivers_specific_rhelversion: []

- name: "Get list of missing drivers to be blacklisted in RHEL 8.1 images"
  set_fact: missing_drivers_allimages="{{ blacklisted_drivers_allimages.results | json_query(jmesquery)}}"
  vars:
    jmesquery: '[?rc==`1`].item'
  when: blacklisted_drivers_allimages is not succeeded

- name: "Get list of missing drivers to be blacklisted in all images"
  set_fact: missing_drivers_specific_rhelversion="{{ blacklisted_drivers_specific_rhelversion.results | json_query(jmesquery)}}"
  vars:
    jmesquery: '[?rc==`1`].item'
  when: blacklisted_drivers_specific_rhelversion is not succeeded


- name: "Write to error msg if some drivers are not blacklisted"
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "\nFailed to blacklist the following drivers"
    create: yes
    state: present
  when: (blacklisted_drivers_allimages is not succeeded) or (blacklisted_drivers_specific_rhelversion is not succeeded)

- name: "Add missing drivers from the blacklist configuration"
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "{{item}} is not blacklisted"
    create: yes
    state: present
  with_items: "{{missing_drivers_allimages + missing_drivers_specific_rhelversion}}"
  when: (blacklisted_drivers_allimages is not succeeded) or (blacklisted_drivers_specific_rhelversion is not succeeded)