###
# This Playbook runs validations which are specific to a VM and 
# doesn't depend on which region the VM is deployed in.
###

---
- name: Set image properties
  set_fact:
    err_folder: /tmp/err
    admin_user: "{{ lookup('env', 'ADMIN_USER_NAME') }}"

#TODO : commenting for now, as this check if failing for rhel7
# - name: Check if Grubenv file is symlink
#   shell: |
#     if [[ -L "/boot/grub2/grubenv" ]]; then   
#       echo "Grubenv file is symlink" >> {{err_folder}}/err_msgs.log
#     fi
#   ignore_errors: yes

- name: Compare RHEL version with the expected RHEL version in the pipeline
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "RHEL version mismatch: Expected RHEL version: {{rhel_version}}, current RHEL version: {{ansible_distribution_version}} "
    create: yes
    state: present
  when: "ansible_distribution_version != rhel_version"

- name: Check number of users on the machine
  shell: getent passwd {1000..60000} | grep -v {{ admin_user }} | wc -l
  register: users_on_machine
  ignore_errors: yes

- name: Collect list of all installed packages
  package_facts:
    manager: "auto"

- name: Check if cloud-init is installed
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "'cloud-init' not found"
    create: yes
    state: present
  when: "'cloud-init' not in ansible_facts.packages"

- name: Write to error msg if repolist failed
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "Additional users found on the machines"
    create: yes
    state: present
  when: users_on_machine.stdout_lines[0] != '0'

- name: check if ADE validation is valid for this vm
  include_tasks: validation-playbooks/ade_packages_validation.yaml
  ignore_errors: yes
  when: ansible_os_family == "RedHat" and (ansible_distribution_major_version == '8' or ansible_distribution_major_version == '7') and (repo_type == 'base' or repo_type =='beta')

- name: Check if blacklisted drivers are blacklisted by modprobe service
  include_tasks: validation-playbooks/blacklisted_drivers_validation.yaml
  ignore_errors: yes
  when: ansible_os_family == "RedHat"

- name: Check if the nvme driver is present in all images
  shell: lsinitrd /boot/initramfs-{{ ansible_facts.kernel }}.img | grep nvme
  register: check_nvme_allimages

- debug:
    var: check_nvme_allimages

- name: "Write to error msg if some drivers are not present"
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "\n NVME validation failed since nvme driver is not present. "
    create: yes
    state: present 
  when: ("nvme" not in check_nvme_allimages.stdout)

- name: Check if the pci driver is present in all images
  shell: lsinitrd /boot/initramfs-{{ ansible_facts.kernel }}.img | grep pci
  register: check_pci_allimages

- debug:
    var: check_pci_allimages

- name: "Write to error msg if some drivers are not present"
  lineinfile:
    path: "{{err_folder}}/err_msgs.log"
    line: "\n PCI validation failed since pci driver is not present. "
    create: yes
    state: present 
  when: ("pci" not in check_pci_allimages.stdout)         